/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tap_u1p8;

import com.mycompany.tap_u1p8.clases.Respuesta;
import javax.swing.JOptionPane;

/**
 *
 * @author chuy-
 */
public class PanelRespuesta extends javax.swing.JPanel {
    private Respuesta respuesta;
    
    public PanelRespuesta() {
        initComponents();
    }
    public PanelRespuesta(Respuesta respuesta){
        this.respuesta = respuesta;
        initComponents();
        jLabelRespuesta.setText(respuesta.getRespuesta());
       jLabelAutorRespuesta.setText(respuesta.getAutorRespuesta());
        jButtonLike.setText(respuesta.getLikes() + "👍");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRespuesta = new javax.swing.JLabel();
        jLabelAutorRespuesta = new javax.swing.JLabel();
        jButtonLike = new javax.swing.JButton();

        jLabelRespuesta.setText("Respuesta");
        jLabelRespuesta.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelAutorRespuesta.setFont(new java.awt.Font("Comic Sans MS", 2, 10)); // NOI18N
        jLabelAutorRespuesta.setText("Autor");

        jButtonLike.setText("0 👍");
        jButtonLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLikeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelAutorRespuesta)
                .addGap(315, 315, 315)
                .addComponent(jButtonLike)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLike)
                    .addComponent(jLabelAutorRespuesta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLikeActionPerformed
        respuesta.setLikes(respuesta.getLikes()+1);
        jButtonLike.setText(respuesta.getLikes() + "👍");
    }//GEN-LAST:event_jButtonLikeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLike;
    private javax.swing.JLabel jLabelAutorRespuesta;
    private javax.swing.JLabel jLabelRespuesta;
    // End of variables declaration//GEN-END:variables
}
