/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tap_u1p8;

import com.google.gson.Gson;
import com.mycompany.tap_u1p8.clases.Respuesta;
import com.mycompany.tap_u1p8.clases.Tema;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author chuy-
 */
public class RespuestasForm extends javax.swing.JFrame {
    public static final String fileRespuestas = "respuestas.json";
    
    private Tema tema;
    private ArrayList<Respuesta> respuestas = new ArrayList<>();
    private ArrayList<Respuesta> respuestasTema = new ArrayList<>();
    
    private GridLayout grid = new GridLayout(1,1);
    
    public RespuestasForm() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public RespuestasForm(Tema tema){
        this.tema= tema;
        initComponents();
        jLabelTema.setText("Tema: " + tema.getTitulo());
        jLabelAutor.setText("Autor: " + tema.getAutor());
        jLabelFecha.setText("Fecha: " + tema.getFecha());
        jPanel1.setLayout(grid);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTema = new javax.swing.JLabel();
        jLabelAutor = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelAutorRespuesta = new javax.swing.JLabel();
        jTextFieldAutorRespuesta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldRespuesta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonGuardarRespuestas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelTema.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTema.setText("Tema");

        jLabelAutor.setText("Autor");

        jLabelFecha.setText("Fecha");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jLabel4.setText("Respuestas");

        jLabelAutorRespuesta.setText("Autor respuesta");

        jLabel2.setText("Respuesta");

        jButton1.setText("Responder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonGuardarRespuestas.setText("Guardar respuestas 💾");
        jButtonGuardarRespuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarRespuestasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonGuardarRespuestas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTema)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelFecha)
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabelAutorRespuesta)
                            .addComponent(jTextFieldAutorRespuesta)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutor)
                    .addComponent(jLabelFecha))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAutorRespuesta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldAutorRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGuardarRespuestas, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        File f = new File(fileRespuestas);
        
        if(f.exists()) {
            leerRespuestas();
            mostrarRespuestas();
        }
    }//GEN-LAST:event_formWindowOpened

    private String generarId() {
        Random r = new Random();
        
        char letra = (char)(r.nextInt(65, 92));
        
        return "" + letra + r.nextInt(1, 9999);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Respuesta nR =new Respuesta(tema.getIdTema(),generarId(),jTextFieldAutorRespuesta.getText(),jTextFieldRespuesta.getText(),0);
        respuestas.add(nR);
        respuestasTema.add(nR);
        grid.setRows(grid.getRows()+1);
        PanelRespuesta panel = new PanelRespuesta(nR);
        jPanel1.add(panel);
        jPanel1.updateUI();
        tema.setRespuestas(tema.getRespuestas()+1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonGuardarRespuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarRespuestasActionPerformed
        Gson gson = new Gson();
        try {
            BufferedWriter bw = new BufferedWriter(
                new FileWriter(fileRespuestas, false)
            );
            String json = gson.toJson(respuestas);
            bw.write(json);
            bw.close();
            
            JOptionPane.showMessageDialog(null, "Se guardo la respuesta");
            
            dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonGuardarRespuestasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RespuestasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RespuestasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RespuestasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RespuestasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RespuestasForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonGuardarRespuestas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelAutorRespuesta;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelTema;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAutorRespuesta;
    private javax.swing.JTextField jTextFieldRespuesta;
    // End of variables declaration//GEN-END:variables

    private void leerRespuestas() {
        Gson gson = new Gson();
        try {
            BufferedReader br = new BufferedReader(
                new FileReader(fileRespuestas)
            );
            String lectura = null;
            String contenido = "";
            while( (lectura = br.readLine()) != null ) {
                contenido += lectura;
            }
            br.close();
            
            JSONParser jsonParser = new JSONParser();
            JSONArray jsonArray = (JSONArray)jsonParser.parse(contenido);
            for (int i = 0; i < jsonArray.size(); i++) {
                Respuesta r = gson.fromJson(jsonArray.get(i).toString(), Respuesta.class);
                
                // Todas las respuestas
                respuestas.add(r);
                
                // Solo las respuestas al tema
                if(r.getIdTema().equals(tema.getIdTema())) {
                    respuestasTema.add(r);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    private void mostrarRespuestas() {
        for(Respuesta r : respuestasTema) {
            grid.setRows(grid.getRows()+1);
            
            PanelRespuesta panel = new PanelRespuesta(r);
            jPanel1.add(panel);
        }
        jPanel1.updateUI();
    }
}
